Update autoinstall_linux

diff --git a/AhMyth-Server/autoinstall_linux b/AhMyth-Server/autoinstall_linux
--- a/AhMyth-Server/autoinstall_linux
+++ b/AhMyth-Server/autoinstall_linux
@@ -1,5 +1,8 @@
 #!/bin/sh
 
+# Get the path to the script's directory
+SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
+
 # Check package manager
 if [ -x "$(command -v apt-get)" ]; then
     PACKAGE_MANAGER="apt-get"
@@ -62,7 +65,7 @@ git_install() {
     clear
 }
 
-dependencies_install() {
+electron_install() {
     echo -e "\nInstalling Electron v11.0.0...\n"
     npm i -g electron@11.0.0
     echo -e "\nDone."
@@ -70,9 +73,35 @@ dependencies_install() {
     clear
 }
 
+create_system_shortcut() {
+    # Create ahmyth file and grant executable permissions
+    echo -e "\nCreating ahmyth file and granting executable permissions...\n"
+    echo '#!/bin/sh' > ahmyth
+    echo "if [ \"\$(id -u)\" = \"0\" ]; then" >> ahmyth
+    echo "    npx electron \"$SCRIPT_DIR/app\" --no-sandbox start" >> ahmyth
+    echo "else" >> ahmyth
+    echo "    npm start --prefix \"$SCRIPT_DIR\"" >> ahmyth
+    echo "fi" >> ahmyth
+    chmod +x ahmyth
+    echo -e "\nahmyth file has been created and executable permissions have been granted."
+    sleep 2
+    clear
+
+    # Move ahmyth file to /usr/local/sbin
+    echo -e "\nMoving ahmyth file to /usr/local/sbin...\n"
+    if [ -d "/usr/local/sbin" ]; then
+        mv ahmyth /usr/local/sbin
+        echo -e "\nahmyth file has been moved to /usr/local/sbin."
+    else
+        echo -e "/usr/local/sbin directory not found! Unable to move ahmyth file."
+    fi
+    sleep 2
+    clear
+}
+
 # Check if user is root
 if [ "$(id -u)" != "0" ]; then
-    echo -e "This script must be run as root!" 1>&2
+    echo -e "This script must be run as root!" >&2
     exit 1
 fi
 
@@ -103,24 +132,36 @@ fi
 
 # Check if nodejs is installed
 if [ -z "$(command -v node)" ]; then
-    echo -e "Node.js is not installed!" 1>&2
+    echo -e "Node.js is not installed!" >&2
     nodejs_install
 fi
 
 # Check if npm is installed
 if [ -z "$(command -v npm)" ]; then
-    echo -e "npm is not installed!" 1>&2
+    echo -e "npm is not installed!" >&2
     npm_install
 fi
 
 # Check if git is installed
 if [ -z "$(command -v git)" ]; then
-    echo -e "Git is not installed!" 1>&2
+    echo -e "Git is not installed!" >&2
     git_install
 fi
 
 # Check if electron v11 is installed
 if [ -z "$(command -v electron)" ]; then
-    echo -e "electron has not been installed by npm!\n" 1>&2
-    dependencies_install
+    echo -e "electron has not been installed by npm!\n" >&2
+    electron_install
+fi
+
+# Check if ahmyth system shortcut exists, create it if not
+if [ -z "$(command -v ahmyth)" ]; then
+    echo -e "\nahmyth system shortcut doesn't exist. Creating..."
+    create_system_shortcut
+fi
+
+# Check if all dependencies are installed
+if [ -x "$(command -v electron)" ] && [ -x "$(command -v node)" ] && [ -x "$(command -v npm)" ] && [ -x "$(command -v git)" ] && [ -f "/usr/local/sbin/ahmyth" ]; then
+    echo -e "\nAll Dependencies are Installed\n"
+    exit 0
 fi
